### ISSUE TITLE
v27 の download が block されました

### ISSUE THREAD

**Issue by topstone** [yssaya/komaochi#1]
有用な software を公開していただきありがとうございます。

Firefox で v27 を download しようとすると、[web page](https://github.com/yssaya/komaochi/releases/tag/v27) (GitHub) は HTTPS なのに [v27 file](http://www.yss-aya.com/aobakomaochi-27-w64-opencl.zip) は HTTP だからということで block されました。

v27 file も GitHub 上に置いていただけると多くの方が困らずに済むと思うのですが、いかがでしょうか。

(それと、些細なことですが、「内臓」→「内蔵」かと。)

**Comment by yssaya** [comment]
Google Drive上に置きました。
最近、GitHubは25MBの制限が出来たようで、60MBのファイルを置けなくなりました。
誤字のご指摘ありがとうございました。

**Comment by topstone** [comment]
素早いご対応ありがとうございます。

GitHub に置ける file size の上限は厳しくなったのですね。(私は [2GiB が上限](https://docs.github.com/ja/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas)だと思い込んでいました。)
