### ISSUE TITLE
2024-04-02 以降、lishogi での対局を受け付けなくなっている

### ISSUE THREAD

**Issue by kachick** [yssaya/komaochi#2]
久しぶりに対局をリクエストしても反応がなく、 https://lishogi.org/@/AobaKomaochi/all を見る限り

https://lishogi.org/AWjhV9m8 UTC 2024/04/01 12:57:14

が最後の棋譜になっているようです。

大変楽しく遊ばせてもらっていた(6枚落ちでも負け越すぐらい軽くあしらわれていた)のですが、lishogi 上の bot は何らかの事情で停止されることになったのでしょうか？

**Comment by yssaya** [comment]
遊んでいただきありがとうございます。
AobaZeroの学習を行ってるマシンでbotを3つ並列で動かしていたのですが
CPUファンが劣化したようで頻繁に勝手にリブートするようになり、
一時的にbotを停止しています。マシンを修理しましたら再稼働させるつもりです。

**Comment by kachick** [comment]
なるほどそういった事情だったのですね。
再稼働を楽しみに待ちつつ、それまでに利用したい場合はローカルで走らせようと思います 🙏
